default:
  serialNumber: "05313416"
  setTemperature: 10
  ROI: [1, 2048, 1, 2048]
  ActiveWidth: 2048
  ActiveHeight: 2048
  ActiveLeftMargin: 54
  ActiveRightMargin: 50
  ActiveTopMargin: 7
  ActiveBottomMargin: 3
  AdcSpeed: 2.0
  AdcAnalogGain: "Medium"
  AdcQuality: "LowNoise"
  ExposureTime: 0
  lastExposed: None
  telescope: '60'
  gain: 1.78
  crpix1: 1075
  crpix2: 974
  cdelt1: -2.5767E-06
  cdelt2: -2.5767E-06
  cdelt1_comment: ".00093"
  cdelt2_comment: ".00093"
  ctype1: 'RA---TAN'
  ctype2: 'DEC--TAN'
  shutter_dict:
    normal: 'Normal'
    closed: 'AlwaysClosed'
    open: 'AlwaysOpen'
  AdcSpeed_States: [.1, 2.0]
  AdcAnalogGain_States: ['Low', 'Medium', 'High']
  AdcQuality_States: ["LowNoise", "HighCapacity", "HighSpeed", "ElectronMultiplied" ]
  lastError: ""