default:
  serialNumber: "04001312"
  setTemperature: 10
  ROI: [1, 2048, 1, 2048]
  ActiveWidth: 2048
  ActiveHeight: 2048
  ActiveLeftMargin: 54
  ActiveRightMargin: 50
  ActiveTopMargin: 7
  ActiveBottomMargin: 3
  AdcSpeed: 2.0
  AdcAnalogGain: "Medium"
  AdcQuality: "LowNoise"
  ExposureTime: 0
  lastExposed: None
  telescope: '60'
  gain: 1.77
  crpix1: 1293
  crpix2: 1280
  cdelt1: -.00010944
  cdelt2: -.00010944
  cdelt1_comment: '.394"'
  cdelt2_comment: '.394"'
  ctype1: 'RA---TAN'
  ctype2: 'DEC--TAN'
  shutter_dict:
    normal: 'Normal'
    closed: 'AlwaysClosed'
    open: 'AlwaysOpen'
  AdcSpeed_States: [.1, 2.0]
  AdcAnalogGain_States: ['Low', 'Medium', 'High']
  AdcQuality_States: ["LowNoise", "HighCapacity", "HighSpeed", "ElectronMultiplied" ]
  lastError: ""